[package]
name = "porta-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
porta-engine = { workspace = true }
porta-dsp = { workspace = true }
hound = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
porta-testkit = { workspace = true }

[features]
default = []
# realtime = ["cpal", "rtrb"]   # enabled in M4
# ui = ["slint"]                # enabled in M5

[lints]
workspace = true
